
# all, phasing, imputation, merge
scenario: "all"

# plink files
# bed: prefix/path/to/plink.bed
bed: data/chip/megaMergedPlus.autosomes.QCedHg38.nonoverlap.bed
# bim: prefix/path/to/plink.bim
bim: data/chip/megaMergedPlus.autosomes.QCedHg38.nonoverlap.bim
# fam: prefix/path/to/plink.fam
fam: data/chip/megaMergedPlus.autosomes.QCedHg38.nonoverlap.fam


phasing:
  input: "vcf"
  shapeit2: "--duohmm -W 5"
  refpanel1: "config/refpanel1.tsv" # mandatory
  refpanel2: "config/refpanel2.tsv" # optional, keep it as empty if no need

imputation:
  shapeit2: "--duohmm -W 5"  # for chip prephasing
  impute2: "-Ne 20000"
  chunksize: 5000000


# if true, do impute2 -merge_ref_panels ref1 ref2 in order
ref1_first: false 

# programs path
impute2: "impute2"
shapeit2: "shapeit2"
plink: "plink"    # plink1.9
bcftools: "bcftools"
dosage: "dosage"  # https://github.com/Zilong-Li/vcfpp/blob/main/tools/dosage.cpp
